version: '3'

services:
  nojavanclub:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    volumes: 
      - .:/nojavanclub
      - nojavanclub_static_volume:/nojavanclub/static
      - nojavanclub_files_volume:/nojavanclub/media
    command: sh -c "python manage.py waitdb && 
                    python manage.py collectstatic --noinput && 
                    python manage.py migrate && 
                    python manage.py runserver 0.0.0.0:8000"
                    # gunicorn --bind :8000 nojavan.wsgi:application"
    restart: always
    env_file: 
      .env
    networks:
      - nojavan_network
      - nginx_network
    depends_on:
      - celery
      - celery-beat
      - nojavan_postgresql
      - redis



  nojavan_postgresql:
    image: postgres:12
    container_name: nojavan_postgresql
    volumes:
      - nojavan_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5431:5432"
    networks:
      - nojavan_network


  redis:
    container_name: 'redis_container'
    image: "redis:latest"
    restart: always
    ports: 
      - "6379:6379"
    command: "redis-server"



  celery:
    build:
      context: .
    command: celery -A nojavan worker -l debug
    volumes:
      - .:/nojavanclub
    # environment:
    #   TEST_BROKER: redis://redis:6379
    depends_on:
      - nojavan_postgresql
      - redis
    restart: always
    env_file: .env
    
  celery-beat:
    build:
      context: .
    command: celery -A nojavan beat -l debug
    volumes:
      - .:/nojavanclub
    depends_on:
      - nojavan_postgresql
      - redis
    restart: always
    env_file: .env
    

volumes:
  nojavan_postgresql:
    external: true
  nojavanclub_static_volume:
    external: true
  nojavanclub_files_volume:
    external: true  
networks:
  nojavan_network:
    external: true
  nginx_network:
    external: true