# Generated by Django 2.2.8 on 2020-05-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('video', models.FileField(blank=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('special', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'منتشر شده'), ('draft', 'پیش نویس'), ('unpublished', 'منتشر نشده')], max_length=11)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
