# Generated by Django 2.2.8 on 2020-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/image/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='favorite/image/%Y-%m-%d'),
        ),
    ]
