# Generated by Django 2.2.10 on 2020-06-05 08:22

from django.db import migrations, models
import nojavan.utils


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200520_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=nojavan.utils.hash_file_name),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=nojavan.utils.hash_file_name),
        ),
    ]
