# Generated by Django 2.2.8 on 2020-05-20 05:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200520_0938'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'امتیاز', 'verbose_name_plural': 'امتیاز ها'},
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'post')},
        ),
    ]
