# Generated by Django 2.2.8 on 2020-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='group/cover/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='group/logo/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
