# Generated by Django 2.2.8 on 2020-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200516_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
