# Generated by Django 2.2.8 on 2020-05-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200516_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], default='male', max_length=6),
            preserve_default=False,
        ),
    ]
