# Generated by Django 2.2.8 on 2020-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200519_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_media',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
