# Generated by Django 2.2.10 on 2020-06-05 08:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200520_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.hash_file_name),
        ),
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.hash_file_name),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.hash_file_name),
        ),
    ]
